namespace:
  name: zabbix-monitoring

rbac:
  create: true
  name: zabbix-kubernetes-discovery
  rolebinding: zabbix-kubernetes-discovery

serviceAccount:
  create: true
  name: zabbix-kubernetes-discovery

deployment:
  name: zabbix-kubernetes-discovery
  image:
    name: ghcr.io/axians-acsp/zabbix-kubernetes-discovery:v1.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  strategy: Recreate

environment:
  ZABBIX_ENDPOINT:
  KUBERNETES_NAME:

crontab:
  name: zabbix-kubernetes-discovery
  schedule:
    discovery: '0 * * * *'
    item: '*/3 * * * *'

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
