name: Build and publish (main)

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY_URL: ghcr.io
  IMAGE_USER: axians-acsp
  IMAGE_NAME: zabbix-kubernetes-discovery

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish
        uses: mr-smithers-excellent/docker-build-push@v5
        if: github.event_name != 'pull_request'
        with:
          addLatest: true
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  vulnerability-scanner:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: github.event_name != 'pull_request'
        with:
          image-ref: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_USER }}/${{ env.IMAGE_NAME }}:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL
      - name: Trivy upload scan results
        uses: github/codeql-action/upload-sarif@v2
        if: github.event_name != 'pull_request'
        with:
          sarif_file: trivy-results.sarif

