name: Build and publish (dev)

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - 'release/**'
      - 'feature/**'
      - 'bugfix/**'

env:
  REGISTRY_URL: ghcr.io
  IMAGE_USER: axians-acsp
  IMAGE_NAME: zabbix-kubernetes-discovery

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish
        uses: mr-smithers-excellent/docker-build-push@v5
        if: github.event_name != 'pull_request'
        with:
          addLatest: false
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
